var coxsbazzer = [
  {
    key: "B00OSTKZWM",
    category: "cox'sbazzer",
    name: "The Spaghetti Dome",
    title: "Cancellation fexibility availiable",
    about: "4 guests 2bedrooms 2beds 2 baths  Wif Air conditioning Kitchen",
    img: "https://i.imgur.com/lvr0NZY.png",
    price: 39,
    star: "4.9(15)",
    totalPrice: 167,
  },
  {
    key: "B01H2E0J5M",
    category: "cox'sbazzer",
    name: "The Original Ship",
    title: "Cancellation fexibility availiable",
    about: "4 guests 2bedrooms 2beds 2 baths  Wif Air conditioning Kitchen",
    img: "https://i.imgur.com/ogvppkR.png",
    price: 39,
    star: "4.5(20)",
    totalPrice: 167,
  },
  {
    key: "B0713WPJKX",
    category: "cox'sbazzer",
    name: "The Waterfront After Dark",
    title: "Cancellation fexibility availiable",
    about: "4 guests 2bedrooms 2beds 2 baths  Wif Air conditioning Kitchen",
    img: "https://i.imgur.com/kndcagr.png",
    price: 39,
    star: "4.9(9)",
    totalPrice: 167,
  },
  {
    key: "B01LPZD1N6",
    category: "cox'sbazzer",
    name: "The Nifty Scarf",
    title: "Cancellation fexibility availiable",
    about: "4 guests 2bedrooms 2beds 2 baths  Wif Air conditioning Kitchen",
    img: "https://i.imgur.com/lvr0NZY.png",
    price: 39,
    star: "4.0(10)",
    totalPrice: 167,
  },
  {
    key: "B01N1SE4EP",
    category: "cox'sbazzer",
    name: "The Bengal Violin",
    title: "Cancellation fexibility availiable",
    about: "4 guests 2bedrooms 2beds 2 baths  Wif Air conditioning Kitchen",
    img: "https://i.imgur.com/ogvppkR.png",
    price: 39,
    star: "4.9(40)",
    totalPrice: 167,
  },
  {
    key: "B017LDNLIG",
    category: "cox'sbazzer",
    name: "The Scarf",
    title: "Cancellation fexibility availiable",
    about: "4 guests 2bedrooms 2beds 2 baths  Wif Air conditioning Kitchen",
    img: "https://i.imgur.com/kndcagr.png",
    price: 39,
    star: " 5(50)",
    totalPrice: 167,
  },
];

export default coxsbazzer;
