var sreemangal = [
  {
    key: "B002RL8IYK",
    category: "sreemangal",
    name: "Elite Camp Resort",
    title: "Cancellation fexibility availiable",
    about: "4 guests 2bedrooms 2beds 2 baths  Wif Air conditioning Kitchen",
    img: "https://i.imgur.com/3FAAHhp.png",
    price: 39,
    star: "4.9(20)",
    totalPrice: 167,
  },
  {
    key: "B01LZ2WZGH",
    category: "sreemangal",
    name: "Private House Hotel",
    title: "Cancellation fexibility availiable",
    about: "4 guests 2bedrooms 2beds 2 baths  Wif Air conditioning Kitchen",
    img: "https://i.imgur.com/nsAMHlV.jpg",
    price: 39,
    star: "4.9(10)",
    totalPrice: 167,
  },
  {
    key: "B01K1IO3QW",
    category: "sreemangal",
    name: "Secluded Tropic Hotel",
    title: "Cancellation fexibility availiable",
    about: "4 guests 2bedrooms 2beds 2 baths  Wif Air conditioning Kitchen",
    img: "https://i.imgur.com/PLuBCfg.jpg",
    price: 39,
    star: "4.5(20)",
    totalPrice: 167,
  },
  {
    key: "B01LD4MGY4",
    category: "sreemangal",
    name: "Queen's Vertex Resort",
    title: "Cancellation fexibility availiable",
    about: "4 guests 2bedrooms 2beds 2 baths  Wif Air conditioning Kitchen",
    img: "https://i.imgur.com/DBfVmlI.jpg",
    price: 39,
    star: "4.5(25)",
    totalPrice: 167,
  },
  {
    key: "B01M18UZF5",
    category: "sreemangal",
    name: "Royal Jewel Hotel",
    title: "Cancellation fexibility availiable",
    about: "4 guests 2bedrooms 2beds 2 baths  Wif Air conditioning Kitchen",
    img: "https://i.imgur.com/Mmrd4iA.jpg",
    price: 39,
    star: "4.1(30)",
    totalPrice: 167,
  },
  {
    key: "B01DBGVB7K",
    category: "sreemangal",
    name: "Crown Prairie Motel",
    title: "Cancellation fexibility availiable",
    about: "4 guests 2bedrooms 2beds 2 baths  Wif Air conditioning Kitchen",
    img: "https://i.imgur.com/Afpfuaj.jpg",
    price: 39,
    star: "4.6(50)",
    totalPrice: 167,
  },
];

export default sreemangal;
