var sundorbon = [
  {
    key: "B016F3M7OM",
    category: "sundorbon",
    name: "Nirvana",
    title: "Cancellation fexibility availiable",
    about: "4 guests 2bedrooms 2beds 2 baths  Wif Air conditioning Kitchen",
    img: "https://i.imgur.com/BUhDrlS.jpg",
    price: 48,
    star: "4.5(62)",
    totalPrice: 167,
  },
  {
    key: "B01MQ0FSS0",
    category: "sundorbon",
    name: "The Caramel Angel",
    title: "Cancellation fexibility availiable",
    about: "4 guests 2bedrooms 2beds 2 baths  Wif Air conditioning Kitchen",
    img: "https://i.imgur.com/z5G1m9S.jpg",
    price: 36,
    star: "4.8(30)",
    totalPrice: 167,
  },
  {
    key: "B01KVIN26O",
    category: "sundorbon",
    name: "The Narrow Whale",
    title: "Cancellation fexibility availiable",
    about: "4 guests 2bedrooms 2beds 2 baths  Wif Air conditioning Kitchen",
    img: "https://i.imgur.com/nLvSIrh.jpg",
    price: 39,
    star: "4.8(21)",
    totalPrice: 167,
  },
  {
    key: "B00UV6I8QQ",
    category: "sundorbon",
    name: "The Savory Tree",
    title: "Cancellation fexibility availiable",
    about: "4 guests 2bedrooms 2beds 2 baths  Wif Air conditioning Kitchen",
    img: "https://i.imgur.com/TrryiJk.jpg",
    price: 44,
    star: "4.5(20)",
    totalPrice: 167,
  },
  {
    key: "B00W68DSWQ",
    category: "sundorbon",
    name: "The Italian Tiger",
    title: "Cancellation fexibility availiable",
    about: "4 guests 2bedrooms 2beds 2 baths  Wif Air conditioning Kitchen",
    img: "https://i.imgur.com/SHOYxAG.jpg",
    price: 50,
    star: "4.9(10)",
    totalPrice: 167,
  },
  {
    key: "B01N6E66RN",
    category: "sundorbon",
    name: "The Chili Boulevard",
    title: "Cancellation fexibility availiable",
    about: "4 guests 2bedrooms 2beds 2 baths  Wif Air conditioning Kitchen",
    img: "https://i.imgur.com/NuUUecD.jpg",
    price: 30,
    star: "4.9(25)",
    totalPrice: 167,
  },
];

export default sundorbon;
